### ISSUE TITLE
blocky 0.17 running in docker/portainer always marked as "unhealthy"

### ISSUE THREAD

**Issue by ikarisan** [0xERR0R/blocky#360]
Hi!

I am running blocky within a docker container. But after upgrading blocky from 0.16 to 0.17 the container is always shwon as "unhealthy".

The last errors (16 within 14 minutes) I got are:

"OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "process_linux.go:95: adding pid 25494 to cgroups caused \"failed to write 25494 to cgroup.procs: write /sys/fs/cgroup/cpu,cpuacct/docker/e9d2d16dc71273df00ba003fdad43d44dcd7b4c146c1de252f422a81be37e252/cgroup.procs: invalid argument\"": unknown

[...]

"time.c:126: Operation not permitted timer.c:617: fatal error: RUNTIME_CHECK(isc_time_now((&now)) == 0) failed Aborted (core dumped)"

The last error repeats every minute. 

Is this a serious problem? How to fix this?`

**Comment by 0xERR0R** [comment]
Do yoh run it on a raspberry pi?

**Comment by ikarisan** [comment]
Yes, I am running it on an RaspberryPi 4

**Comment by 0xERR0R** [comment]
Its a bug in raspbian, see https://github.com/alpinelinux/docker-alpine/issues/110

You can either install libseccomp2 from backports or updrade to newer raspbian version.

You can also temporarily disable healthcheck in your docker-compose

**Comment by ikarisan** [comment]
Diasbling healthcheck did the trick. 
Installing libseccomp2 from backports did not change anything. :( 


> Its a bug in raspbian, see [alpinelinux/docker-alpine#110](https://github.com/alpinelinux/docker-alpine/issues/110)
> 
> You can either install libseccomp2 from backports or updrade to newer raspbian version.
> 
> You can also temporarily disable healthcheck in your docker-compose

**Comment by 0xERR0R** [comment]
I had the same problem with navidrome in docker on pi3 (https://github.com/navidrome/navidrome/issues/773), but it was fixed after I updated the libseccomp package. My blocky (latest dev version) is healthy now.

**Comment by kwitsch** [comment]
I'm using the the image from [timebertt ](https://github.com/timebertt/pi-cloud-init)for 3/4 year on PI-2/3/4 without a problem.

blocky 0.17 deployed as stack with portainer on a 5 node swarm(3 manager) without a problem(healthcheck enabled & no errors).

configuration snippets
----
cloud-config:
```
package_update: true
package_upgrade: true
package_reboot_if_required: true

apt:
  sources:
    docker.list:
      source: deb [arch=arm64,armhf] https://download.docker.com/linux/debian $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - docker-ce
  - docker-ce-cli
 ```

service definition:
```
  blocky:
    image: spx01/blocky
    logging: *logging
    networks: *network-internal
    deploy: *deploy-endpoint
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
    configs:
      - source: blocky_config
        target: /app/config.yml
    environment:
      TZ: Europe/Berlin
```

**Comment by 0xERR0R** [comment]
If I understand it right, the problem occurs only on arm7 and only with older raspbian/debian (<= buster). OS upgrade or installation of libseccomp2 from backport solves the problem. This problem occurs since upgrade to alpine 3.13.
